[package]
name = "lychnos-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lychnos-core = { path = "../lychnos-core" }
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true
getrandom.workspace = true
