#!/usr/bin/env bash
set -euo pipefail

CLASS="auto"

usage() {
  cat <<'EOF'
Usage: ./scripts/install-local-brain-llama.sh [--class tiny|compact|standard|large|auto]

Installs the llama.cpp local-brain adapter in user-owned locations and selects
an official Apache-2.0 Qwen3 GGUF model appropriate for this desktop/laptop body.

This script is for llama.cpp-capable desktop bodies. Android, iOS, and Pocket
Lychnos use the same model-class contract but may use different installers or
inference runtimes.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --class)
      CLASS="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$CLASS" in
  auto|tiny|compact|standard|large) ;;
  *)
    echo "Invalid local-brain class: $CLASS" >&2
    exit 2
    ;;
esac

for command in curl python3; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "Missing required command: $command" >&2
    exit 1
  fi
done

memory_mib() {
  case "$(uname -s)" in
    Linux)
      awk '/MemTotal:/ { printf "%d\\n", $2 / 1024 }' /proc/meminfo
      ;;
    Darwin)
      python3 - <<'PY'
import subprocess
value = int(subprocess.check_output(["sysctl", "-n", "hw.memsize"]))
print(value // (1024 * 1024))
PY
      ;;
    *)
      echo 0
      ;;
  esac
}

if [[ "$CLASS" == "auto" ]]; then
  mem="$(memory_mib)"
  if (( mem < 6144 )); then
    CLASS="tiny"
  elif (( mem < 12288 )); then
    CLASS="compact"
  elif (( mem < 32768 )); then
    CLASS="standard"
  else
    CLASS="large"
  fi
fi

case "$CLASS" in
  tiny)
    MODEL_SPEC="Qwen/Qwen3-0.6B-GGUF:Q8_0"
    CONTEXT=4096
    ;;
  compact)
    MODEL_SPEC="Qwen/Qwen3-1.7B-GGUF:Q8_0"
    CONTEXT=4096
    ;;
  standard)
    MODEL_SPEC="Qwen/Qwen3-4B-GGUF:Q4_K_M"
    CONTEXT=8192
    ;;
  large)
    MODEL_SPEC="Qwen/Qwen3-8B-GGUF:Q4_K_M"
    CONTEXT=8192
    ;;
esac

CACHE_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}/lychnos"
INSTALLER="$CACHE_ROOT/llama-install.sh"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lychnos"
BRAIN_ENV="$CONFIG_DIR/brain.env"

mkdir -p "$CACHE_ROOT" "$CONFIG_DIR"

echo "Installing llama.cpp local runtime for this body..."
curl -LsSf https://llama.app/install.sh -o "$INSTALLER"
sh "$INSTALLER"

LLAMA_BIN="$HOME/.local/bin/llama"
if [[ ! -x "$LLAMA_BIN" ]]; then
  echo "llama runtime did not install at $LLAMA_BIN" >&2
  exit 1
fi

echo
echo "Selected local-brain class: $CLASS"
echo "Selected model: $MODEL_SPEC"
echo "Downloading model into llama.cpp user cache..."
"$LLAMA_BIN" download -hf "$MODEL_SPEC"

cat > "$BRAIN_ENV" <<EOF
# Machine-local Lychnos local-brain selection.
# Generated by install-local-brain-llama.sh.
LYCHNOS_LOCAL_BRAIN_ENABLED=1
LYCHNOS_LOCAL_BRAIN_RUNTIME=$LLAMA_BIN
LYCHNOS_LOCAL_BRAIN_MODEL=$MODEL_SPEC
LYCHNOS_LOCAL_BRAIN_PORT=18181
LYCHNOS_LOCAL_BRAIN_CONTEXT=$CONTEXT
LYCHNOS_LOCAL_BRAIN_USER_SUFFIX=/no_think
EOF

echo
echo "Local Lychnos brain installed for this body."
echo "Class:  $CLASS"
echo "Runtime: $LLAMA_BIN"
echo "Model:   $MODEL_SPEC"
echo "Config:  $BRAIN_ENV"
echo
echo "Restart Lychnos with: lychnos restart"
